### ISSUE TITLE
IfExecuteNode masks older IfExecute

### ISSUE THREAD

**Issue by AlexeyKravtsov1987** [theUpsider/ComfyUI-Logic#17]
Newer [IfExecuteNode](https://github.com/theUpsider/ComfyUI-Logic/blob/ae0ca532177eef7325d207f8b8a2f88f4d1a837c/nodes.py#L239) has exactly the same name as the older IfExecute, masking the latter and making it unusable/unselectable/etc
![image](https://github.com/user-attachments/assets/2fd1d6af-254c-4f75-9886-ea713d595252)

**Comment by alessandroperilli** [comment]
That's why it's not working. I was going crazy.

**Comment by theUpsider** [comment]
Wow great find thanks. Will fix today.

**Comment by alessandroperilli** [comment]
@theUpsider, given that you plan to update it (thank you!), please know that, since this morning, the new ComfyUI Frontend is enforced by default (at least in my installation) and it breaks your Compare node:

<img width="1454" alt="Screenshot 2024-08-16 at 10 10 19" src="https://github.com/user-attachments/assets/6da5f799-cd09-43ba-9c3d-dd174126612a">

**Comment by theUpsider** [comment]
@alessandroperilli thanks for the hint. I'll tackle this as well

**Comment by theUpsider** [comment]
I updated the repo. Still working on the If ANY execute node. But its difficult. 

Feel free to open another issue, if any errors arise. Will mark this as closed.

**Comment by alessandroperilli** [comment]
The `IF ANY return A else B` is now working, thank you @theUpsider. However, the Compare node is still missing in action.

As a side question: is it possible to expand this node so that it compares against multiple variables instead of just two?

My problem is trying to compare an input against 5 possible alternatives. My current approach is the following and it works, but it's quite crude and it takes a load of space on the canvas:

<img width="980" alt="Screenshot 2024-08-16 at 12 24 39" src="https://github.com/user-attachments/assets/054c7ab6-dd5b-4ffd-b770-617dfea6cdbb">

**Comment by theUpsider** [comment]
@alessandroperilli no worries ^^

Which node are you referring to when you say "Compare node"?
And there might be a solution to your other problem. I will try to implement something. The difficulty lies within the dynamic nature of arrays and comparison. I feel like having to dig deep into comfy source code 😅

**Comment by alessandroperilli** [comment]
@theUpsider Thanks for looking into this. 

I was certain that in your node suite there was a "Compare" node, performing a comparison between input A and B, but I must be mistaken. It doesn't matter: I replaced it with a similar node from another suite. Sorry for the confusion.

**Comment by theUpsider** [comment]
@alessandroperilli I did have a compare node. But the new Comfy update seem to have broken this as well. Ill push another commit. Crazy how I didnt notice it yet.

**Comment by theUpsider** [comment]
I pushed a commit to fix the Compare Node. Should be working now.
